---
title: "figure3"
author: "Yang Zhang"
date: "7/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knitr)
library(BiocStyle)

.cran_packages <- c("ggplot2", "here", "dplyr", "ggpubr", "vegan")
.bioc_packages <- c("dada2", "phyloseq", "DESeq2")
.inst <- .cran_packages %in% installed.packages()
if(any(!.inst)) {
   install.packages(.cran_packages[!.inst])
}
.inst <- .bioc_packages %in% installed.packages()
if(any(!.inst)) {
   source("http://bioconductor.org/biocLite.R")
   biocLite(.bioc_packages[!.inst], ask = F)
}
# Load packages into session, and print package version
sapply(c(.cran_packages, .bioc_packages), require, character.only = TRUE)
theme_set(theme_bw())
```


```{r phyloseq object: without tree}
asv_counts <- read.table(here("ASVs_counts_gg.txt"), header = T)
meta_data <- read.table(here("sampledata.txt"), row.names = 1)
taxa <- read.table(here("ASVs_taxonomy_gg.txt"), header = T, 
                   stringsAsFactors = FALSE, sep = "\t", fill = TRUE, quote = "")

rownames(taxa) <- rownames(asv_counts)

asv_counts <- asv_counts %>% 
  mutate_if(is.integer, as.numeric)
asv_counts <- asv_counts %>% 
  mutate_if(is.factor, as.character)

rownames(asv_counts) <- rownames(taxa)
taxa <- as.matrix(taxa)

asv_c = otu_table(asv_counts, taxa_are_rows = T)
tax = tax_table(taxa)
sampledata = sample_data(meta_data)
#tree = phy_tree(fitGTR$tree)
#physeq <- merge_phyloseq(sampledata, asv_c, tax, tree)
physeq <- merge_phyloseq(sampledata, asv_c, tax)
physeq
```


```{r phyloseq object: with tree}
phy.tree <- readRDS(here("phyloseq_wtree.rds"))
```


```{r beta diversity: physeq}
################################################### counts ####################################################
psFR.pc.uni <- ordinate(phy.tree, method="PCoA", distance = "bray") 
#Then we can see how much of total distance is captured by the eigenvalues 
plot_scree(psFR.pc.uni, 'Scree plot, Bray-Curtis/PCoA')

## How much variation do the ﬁrst two axes (ones we will plot) explain?

(100*sum(psFR.pc.uni$values$Relative_eig[1:2]))  ## 65.73144

q <- plot_ordination(phy.tree, psFR.pc.uni,color="Diet") 
allcolors <- c("#0074C2", "#D3AA3D", "#868686", "#C75952")
qq <- q + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +   ## n < 30
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  labs(title = "Bray-Curtis") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 15),
        legend.text = element_text(size = 20), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 20, face = "bold")) 

ggsave(here("results/figures", "Figure3_counts.png"), width = 12, height = 8)


qq <- qq + theme(legend.position="none",
                      axis.title.y = element_text(size = 18),
                      axis.text.y = element_text(size = 10),
                      axis.text.x = element_text(size = 15)) +
  scale_y_continuous(position = "right")



################################################# Relative Abundance #################################################

# Transform data to proportions as appropriate for Bray-Curtis distances
ps.prop <- transform_sample_counts(physeq, function(x) x/sum(x))

pca.ord <- ordinate(ps.prop, method = "PCoA")


p <- plot_ordination(ps.prop, pca.ord, color = "Diet")

pp <- p + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  labs(title = "Bray-Curtis") +    
  #xlab(paste("PC1 - ", "41%", sep = "")) +
  #ylab(paste("PC2 - ", "29.5%", sep = "")) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 15),
        legend.text = element_text(size = 15), 
        plot.margin = margin(1, 1, 0, 0, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 15, face = "bold")) 

ggsave(here("results/figures", "Figure3_beta_diversity.png"), width = 12, height = 8)

## perform adonis with phyloseq
metadt_pc <- as(sample_data(physeq), "data.frame")
set.seed(2018)
adonis(phyloseq::distance(physeq, method="bray") ~ Diet, data = metadt_pc)

####################################################### NMDS #########################################################

pca.ord1 <- ordinate(ps.prop, method = "NMDS")

p2 <- plot_ordination(ps.prop, pca.ord1, color = "Diet")
p2 + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse() +
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 20), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 20, face = "bold"))


```


```{r beta diversity: seqtab}
################################################### counts ####################################################
phy.tree <- readRDS(here("phyloseq_wtree.rds"))
rank_names(phy.tree)
table(tax_table(phy.tree)[, "Phylum"], exclude = NULL)
#ps0 <- subset_taxa(phy.tree, !is.na(Phylum) & !Phylum %in% c("", "uncharacterized"))

#seqtab <- readRDS(here("seqtab.rds"))
psFR <- ordinate(phy.tree, method="MDS", distance = "unifrac") 
#Then we can see how much of total distance is captured by the eigenvalues 
plot_scree(psFR, 'Scree plot, unifrac/PCoA')

## How much variation do the ﬁrst two axes (ones we will plot) explain?

(100*sum(psFR$values$Relative_eig[1:2]))  ## 18.48

qs <- plot_ordination(phy.tree, psFR,color="Diet") 
qqs <- qs + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +   ## n < 30
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 20), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 20, face = "bold")) 

ggsave(here("results/figures", "Figure3_counts.png"), width = 12, height = 8)


qq <- qq + theme(legend.position="none",
                      axis.title.y = element_text(size = 18),
                      axis.text.y = element_text(size = 10),
                      axis.text.x = element_text(size = 15)) +
  scale_y_continuous(position = "right")



################################################# Relative Abundance #################################################

# Transform data to proportions as appropriate for Bray-Curtis distances
ps.prop <- transform_sample_counts(physeq, function(x) x/sum(x))

pca.ord <- ordinate(ps.prop, method = "PCoA")



allcolors <- c("#a2bba7", "#f8d1ac", "#eb9391", "#9572bf")

p <- plot_ordination(ps.prop, pca.ord, color = "Diet")

pp <- p + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 15), 
        plot.margin = margin(1, 0, 0, 1, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 15, face = "bold")) 

ggsave(here("results/figures", "Figure3_beta_diversity.png"), width = 12, height = 8)

## perform adonis with phyloseq
metadt_pc <- as(sample_data(physeq), "data.frame")
set.seed(2018)
adonis(phyloseq::distance(physeq, method="bray") ~ Diet, data = metadt_pc)

####################################################### NMDS #########################################################

pca.ord1 <- ordinate(ps.prop, method = "NMDS")
pca.ord2 <- ordinate(ps.prop, method = "jaccard")
p2 <- plot_ordination(ps.prop, pca.ord2, color = "Diet")
p2 + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse() +
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 20), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 20, face = "bold"))


```


## unweighted unifrac

```{r}
## remove the OTUs that included all unassigned sequences ("-1")
## 
seqtab1 <- subset_taxa(phy.tree, Genus != "-1")
seqtabss.dist <- phyloseq::distance(seqtab1, "uunifrac")
seqtabsw.dist <- phyloseq::distance(seqtab1, "wunifrac")
seqtabss.ordi <- ordinate(seqtab1, "PCoA", seqtabss.dist)
seqtabsw.ordi <- ordinate(seqtab1, "PCoA", seqtabsw.dist)
plot_ordination(seqtab1, seqtabss.ordi, color = "Diet")

## unweighted
a <- plot_ordination(seqtab1, seqtabss.ordi, color="Diet") 
an <- a + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +   ## n < 30
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  labs(title = "Unweighted UniFrac") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 15),
        legend.text = element_text(size = 15), 
        plot.margin = margin(1, 1, 0, 0, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 15, face = "bold"))

## perform adonis with phyloseq
ado1 <- as(sample_data(phy.tree), "data.frame")
set.seed(2018)
adonis(phyloseq::distance(phy.tree, method="bray") ~ Diet, data = ado1)




## weighted
b <- plot_ordination(seqtab1, seqtabsw.ordi, color="Diet") 

bn <- b + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +   ## n < 30
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  labs(title = "Weighted UniFrac") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 15),
        legend.text = element_text(size = 15), 
        plot.margin = margin(1, 1, 0, 0, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 15, face = "bold"))



## available distance methods:

unlist(distanceMethodList)

## calculate distance matrix
seqtab.dist <- phyloseq::distance(phy.tree, "uunifrac")
seqtab1.dist <- phyloseq::distance(phy.tree, method = "wunifrac")

## calculate ordination
seqtab.ordi <-  ordinate(phy.tree, "PCoA", seqtab.dist) ## what if i reduce the variables in the sample data?
seqtab1.ordi <- ordinate(phy.tree, "PCoA", seqtab1.dist)

#Then we can see how much of total distance is captured by the eigenvalues 
plot_scree(seqtab.ordi, 'Scree plot, unifrac-PCoA ordination eigenvalues')
plot_scree(seqtab1.ordi, 'Scree plot, unifrac-PCoA ordination eigenvalues')

## How much variation do the ﬁrst two axes (ones we will plot) explain?
(100*sum(seqtab.ordi$values$Relative_eig[1:2]))  ## 18.55
(100*sum(seqtab1.ordi$values$Relative_eig[1:2])) ## 90.58

ordu = ordinate(phy.tree, "PCoA", "uunifrac")
orduw = ordinate(phy.tree, "MDS", "wunifrac")

plot_ordination(phy.tree, seqtab.ordi, color = "Diet")
plot_ordination(phy.tree, seqtab1.ordi, color = "Diet")


seqtab.ordi <-  ordinate(seqtab.dist, "MDS", "uunifrac")

```

```{r}
m <- plot_ordination(phy.tree, seqtab.ordi, color="Diet") 
allcolors <- c("#a2bba7", "#f8d1ac", "#eb9391", "#9572bf")
n <- m + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +   ## n < 30
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 15), 
        plot.margin = margin(1, 1, 0, 0, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 15, face = "bold"))  

n <- n + theme(legend.position="none")
p <- p + theme(legend.position="none")
qq <- qq + theme(legend.position="none") +
  scale_y_continuous(position = "right")

pp1 <- pp + scale_y_continuous(position = "right")

ggsave(here("figures", "Figure3_beta_diversity_unifrac.png"), width = 12, height = 8)

mw <- plot_ordination(phy.tree, seqtab1.ordi, color="Diet") 
nw <- mw + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +   ## n < 30
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 10), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 10, face = "bold"))# +
  #scale_y_continuous(position = "right")

n <- n + theme(legend.position="none")
nw <- nw + theme(legend.position="none") +
  scale_y_continuous(position = "right")

qq <- qq + theme(legend.position="none") +
  scale_y_continuous(position = "right")

ggsave(here("figures", "Figure3_beta_diversity_unifrac.png"), width = 12, height = 8)
```

```{r}
ggarrange(an, 
          bn,
          pp,
          align = "h",
          labels = c("unifrac", "wunifrac", "bray", ""), 
          #font.label = list(size = 15, color = "black"),
          legend = c("bottom"),
          common.legend = TRUE)

ggsave(here("figures", "Figure3_unifrac.png"), width = 12, height = 12)



ggarrange(an, 
          bn,
          pp,
          #qq,
          #ff,
          ncol = 2, nrow = 2,
          align = "hv",
          labels = c("A", "B", "C"), 
          font.label = list(size = 15, color = "black"),
          legend = c("bottom"),
          #label.x.npc = 0.4, 
          #label.y.npc = 1, 
          hjust = -0.4, vjust = 2,
          common.legend = TRUE)
ggsave(here("Figure3-new.png"), width = 16, height = 14)
```

