---
title: "figure3"
author: "Yang Zhang"
date: "7/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knitr)
library(BiocStyle)

.cran_packages <- c("ggplot2", "here", "dplyr", "ggpubr", "vegan")
.bioc_packages <- c("dada2", "phyloseq", "DESeq2")
.inst <- .cran_packages %in% installed.packages()
if(any(!.inst)) {
   install.packages(.cran_packages[!.inst])
}
.inst <- .bioc_packages %in% installed.packages()
if(any(!.inst)) {
   source("http://bioconductor.org/biocLite.R")
   biocLite(.bioc_packages[!.inst], ask = F)
}
# Load packages into session, and print package version
sapply(c(.cran_packages, .bioc_packages), require, character.only = TRUE)
theme_set(theme_bw())
```


```{r phyloseq object: without tree}
asv_counts <- read.table(here("results/analyses/Figure3", "ASVs_counts_gg.txt"), header = T)
meta_data <- read.table(here("results/analyses/Figure3", "sampledata.txt"), row.names = 1)
taxa <- read.table(here("results/analyses/Figure3", "ASVs_taxonomy_gg.txt"), header = T, 
                   stringsAsFactors = FALSE, sep = "\t", fill = TRUE, quote = "")

rownames(taxa) <- rownames(asv_counts)

asv_counts <- asv_counts %>% 
  mutate_if(is.integer, as.numeric)
asv_counts <- asv_counts %>% 
  mutate_if(is.factor, as.character)

rownames(asv_counts) <- rownames(taxa)
taxa <- as.matrix(taxa)

asv_c = otu_table(asv_counts, taxa_are_rows = T)
tax = tax_table(taxa)
sampledata = sample_data(meta_data)
(physeq <- merge_phyloseq(sampledata, asv_c, tax))
```


```{r phyloseq object: with tree}
phy.tree <- readRDS(here("results/analyses/Figure3", "phyloseq_wtree.rds"))
```

## Bray-Curtis distances
```{r}
# Transform data to proportions as appropriate for Bray-Curtis distances
ps.prop <- transform_sample_counts(physeq, function(x) x/sum(x))
pca.ord <- ordinate(ps.prop, method = "PCoA")
p <- plot_ordination(ps.prop, pca.ord, color = "Diet")

allcolors <- c("#0074C2", "#D3AA3D", "#868686", "#C75952")

BC <- p + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
    labs(title = "Bray-Curtis") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 15),
        legend.text = element_text(size = 15), 
        plot.margin = margin(1, 1, 0, 0, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 15, face = "bold"))
```


## unweighted unifrac
```{r}
## remove the ASVs that included all unassigned sequences ("-1")
seqtab1 <- subset_taxa(phy.tree, Genus != "-1")
seqtabss.dist <- phyloseq::distance(seqtab1, "uunifrac")
seqtabsw.dist <- phyloseq::distance(seqtab1, "wunifrac")
seqtabss.ordi <- ordinate(seqtab1, "PCoA", seqtabss.dist)
seqtabsw.ordi <- ordinate(seqtab1, "PCoA", seqtabsw.dist)

a <- plot_ordination(seqtab1, seqtabss.ordi, color="Diet") 
an <- a + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +   ## n < 30
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  labs(title = "Unweighted UniFrac") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 15),
        legend.text = element_text(size = 15), 
        plot.margin = margin(1, 1, 0, 0, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 15, face = "bold"))

## perform adonis with phyloseq
ado1 <- as(sample_data(phy.tree), "data.frame")
set.seed(2018)
adonis(phyloseq::distance(phy.tree, method="bray") ~ Diet, data = ado1)
```


## weighted unifrac
```{r}
b <- plot_ordination(seqtab1, seqtabsw.ordi, color="Diet") 
bn <- b + geom_point(size = 4) +
  scale_color_manual(values = allcolors) +
  stat_ellipse(type = "t", level = 0.95) +   ## n < 30
  geom_vline(xintercept = 0, alpha = 0.15) +
  geom_hline(yintercept = 0, alpha = 0.15) +
  labs(title = "Weighted UniFrac") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 15),
        legend.text = element_text(size = 15), 
        plot.margin = margin(1, 1, 0, 0, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size = 15, face = "bold"))
```


```{r}
ggarrange(BC,
          an, 
          bn,
          ncol = 2, nrow = 2,
          align = "hv",
          labels = c("A", "B", "C"), 
          font.label = list(size = 15, color = "black"),
          legend = c("bottom"),
          hjust = -0.4, vjust = 2,
          common.legend = TRUE)
ggsave(here("Figure3.png"), width = 16, height = 14)
```

