---
title: "figure7"
author: "Yang Zhang"
date: "11/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(ggfortify)
library(cluster)
library(ggpubr)
library(factoextra)
library(tidyverse)

set.seed(1314)

## data modify
genes = read.table(here("genes.txt"), header = T)
gene_sub <- genes %>%
  filter(treatment == "1.HFD" | treatment == "4.TXN")
dfg <- gene_sub[c(3:24)]
gene_centered <- scale(dfg, center = TRUE, scale = TRUE)


## calculate eigenvalues
pca.var.g <- prcomp(gene_centered)$sdev^2
pca.var.per.g <- round(pca.var.g/sum(pca.var.g)*100, 1)

## A: PCA plot

gene_BA <- fviz_pca_biplot(prcomp(gene_centered), axes = c(1,2),
                geom.ind = "point", geom.var = "arrow",
                pointshape = 21, pointsize = 4,
                fill.ind = gene_sub$treatment, col.ind = "black",
                col.var = factor(c("bile acid synthesis", "bile acid synthesis", "bile acid synthesis", "bile acid synthesis", "bile acid synthesis", "Fxr", "fatty acid synthesis", "fatty acid synthesis", "fatty acid synthesis","inflammation", "inflammation", "inflammation", "inflammation", "inflammation", "inflammation", "inflammation", "barrier integrity", "barrier integrity", "barrier integrity", "barrier integrity", "barrier integrity", "inflammation")),
                select.var = list(name = c("BA.met_lv_cyp27a1", "BA.met_lv_shp", "BA.met_lv_cyp7a1", "BA.met_lv_fxr", "FA_lv_srebp1c", "FA_lv_nqo1", "FA_lv_scd1", "inflammation_lv_tnfa", "inflammation_lv_Il1b", "inflammation_wat_ccl2","inflammation_wat_f480","inflammation_wat_TNFa", "inflammation_wat_IL6","inflammation_wat_Il1b", "BI_cn_occludin","BI_cn_IL22", "BI_cn_cox2", "BI_cn_jam3")),
                addEllipses = TRUE,
                title = "Differentialy expressed genes stratify HFD and TXN", 
                xlab = paste("PC1 - ", pca.var.per.g[1], "%", sep = ""),
                ylab = paste("PC2 - ", pca.var.per.g[2], "%", sep = ""),
                legend.title = list(fill = "treatment", color = ""),
                ggtheme = theme_bw(),
                mean.point = FALSE, repel = TRUE       
             ) +
  ggpubr::fill_palette(c("#0072BF", "#CF524C"))+      
  ggpubr::color_palette(c("cyan", "blue", "green", "grey", "red"))+
  theme(axis.title = element_text(size = 15),
        legend.position = "bottom",
        plot.margin = unit(c(0.3,1,0.3,0.3), "cm"))

gene_BA + guides(fill=guide_legend(nrow=2)) -> gene_BA

## B: individual gene expression
library(gglayer)
library(reshape2)



lapply(gene_sub[, c("inflammation_lv_tnfa", "inflammation_lv_Il1b", "inflammation_wat_ccl2",
                    "inflammation_wat_TNFa", "inflammation_wat_IL6", "inflammation_wat_f480")], function(x) t.test(x ~ gene_sub$treatment, var.equal = TRUE))

dat.inflam <- melt(gene_sub,id.vars='treatment', groups = 'treatment', 
              measure.vars=c('inflammation_lv_tnfa', 'inflammation_lv_Il1b', 'inflammation_wat_ccl2', 'inflammation_wat_f480', 'inflammation_wat_TNFa', 'inflammation_wat_IL6'))

significant_genes <- c(
    'inflammation_wat_ccl2' = 'WAT Ccl2***, p < 0.001',
    'inflammation_wat_f480' = 'WAT F4/80*, p = 0.016',
    'inflammation_wat_IL6' = 'WAT Il-6*, p = 0.049', 
    'inflammation_wat_TNFa' = 'WAT TNF-α*, p = 0.032',
    "inflammation_lv_tnfa" = "LV TNF-α, p = 0.081",
    "inflammation_lv_Il1b" = "LV Il-1β*, p = 0.039"
)


p <- ggplot(dat.inflam, aes(treatment, log(value), fill=treatment), outlier.shape = NA)  +
    ylab("") +
    xlab("") +
    ggtitle("2. Inflammatory Genes") +
    geom_flat_violin(position=position_nudge(x=.1)) +
    geom_dotplot(binaxis="y", stackdir="down", dotsize=.35) +
    geom_boxplot(width=.1, position=position_nudge(x=.1)) +
    scale_x_discrete(expand=c(1,0)) +
    scale_fill_manual(values=c("#0072BF", "#CF524C")) +
    coord_flip() + theme_bw() +
    theme(legend.position="none", 
          strip.text = element_text(face = "bold.italic", size = 12), 
          strip.background = element_rect(fill = "#99B6C2"),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.x = element_text(size = 12),
          axis.title = element_text(size = 15, face = "bold"),
          plot.margin = unit(c(0,1,0,0.3), "cm"))

p <- p + facet_wrap(~ variable, labeller = as_labeller(significant_genes), ncol = 3)


### barrier defense

lapply(gene_sub[, c("BI_cn_cox2", "BI_cn_occludin", "BI_cn_IL22")], function(x) t.test(x ~ gene_sub$treatment, var.equal = TRUE))

dat.bar <- melt(gene_sub,id.vars='treatment', groups = 'treatment', 
              measure.vars=c('BI_cn_IL22', 'BI_cn_cox2', 'BI_cn_occludin'))

significant_genes_bar <- c(
    "BI_cn_IL22" = "CN Il-22**, p = 0.003",
    'BI_cn_cox2' = 'CN Cox2***, p < 0.001 ',
    'BI_cn_occludin' = 'CN Ocln, p = 0.08'
)


p2 <- ggplot(dat.bar, aes(treatment, log(value), fill=treatment), outlier.shape = NA)  +
    ylab("\nlog2(fold change)") +
    xlab("") +
    ggtitle("3. Barrier Defense Genes") +
    geom_flat_violin(position=position_nudge(x=.1)) +
    geom_dotplot(binaxis="y", stackdir="down", dotsize=.35) +
    geom_boxplot(width=.1, position=position_nudge(x=.1)) +
    scale_x_discrete(expand=c(1,0)) +
    scale_fill_manual(values=c("#0072BF", "#CF524C")) +
    coord_flip() + theme_bw() +
    theme(legend.position="none", 
          strip.text = element_text(face = "bold.italic", size = 12), 
          strip.background = element_rect(fill = "#99B6C2"),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.x = element_text(size = 12),
          axis.title = element_text(size = 15, face = "bold"),
          plot.margin = unit(c(0.3,1,0,0.3), "cm"))

p2 <- p2 + facet_wrap(~ variable, labeller = as_labeller(significant_genes_bar), nrow = 1)


### BA metabolism

lapply(gene_sub[, c("BA.met_lv_cyp27a1", "BA.met_lv_cyp8b1", "BA.met_lv_Bsep", "BA.met_lv_shp",
                    "BA.met_lv_cyp7a1", "BA.met_lv_fxr", "FA_lv_srebp1c", "FA_lv_nqo1", "FA_lv_scd1", "BA.met_lv_cyp27a1", "BA.met_lv_cyp8b1")], function(x) t.test(x ~ gene_sub$treatment, var.equal = TRUE))

dat.bametab <- melt(gene_sub,id.vars='treatment', groups = 'treatment', 
              measure.vars=c("BA.met_lv_fxr", "BA.met_lv_shp","BA.met_lv_cyp7a1", "BA.met_lv_Bsep", "BA.met_lv_cyp8b1", "BA.met_lv_cyp27a1"))

significant_genes_bametab <- c(
    "BA.met_lv_fxr" = "LV Fxr, p = 0.20",
    'BA.met_lv_cyp7a1' = 'LV Cyp7a1**, p = 0.007 ',
    'BA.met_lv_shp' = 'LV Shp, p = 0.055',
    "BA.met_lv_Bsep" = "LV Bsep*, p = 0.022",
    "BA.met_lv_cyp27a1" = "LV Cyp27a1, p = 0.24",
    "BA.met_lv_cyp8b1" = "LV Cyp8b1, p = 0.64"
)


p3 <- ggplot(dat.bametab, aes(treatment, log(value), fill=treatment), outlier.shape = NA)  +
    ylab("") +
    xlab("") +
    ggtitle("1. Bile Acid Metabolism Genes") +
    geom_flat_violin(position=position_nudge(x=.1)) +
    geom_dotplot(binaxis="y", stackdir="down", dotsize=.35) +
    geom_boxplot(width=.1, position=position_nudge(x=.1)) +
    scale_x_discrete(expand=c(1,0)) +
    scale_fill_manual(values=c("#0072BF", "#CF524C")) +
    coord_flip() + 
    theme_bw() +
    theme(legend.position="none", 
          strip.text = element_text(face = "bold.italic", size = 12), 
          strip.background = element_rect(fill = "#99B6C2"),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.x = element_text(size = 12),
          axis.title = element_text(size = 15, face = "bold"),
          plot.margin = unit(c(0.3,1,0,0.3), "cm"))

p3 <- p3 + facet_wrap(~ variable, labeller = as_labeller(significant_genes_bametab), 
                      ncol = 3, nrow = 2)
```


```{r p4: fatty acid synthesis}

lapply(gene_sub[, c("FA_lv_srebp1c", "FA_lv_scd1")], function(x) t.test(x ~ gene_sub$treatment, var.equal = TRUE))

dat.chol <- melt(gene_sub, id.vars='treatment', groups = 'treatment', 
              measure.vars=c("FA_lv_srebp1c", "FA_lv_scd1", "BA.met_lv_cyp8b1"))

significant_genes_chol <- c(
    'BA.met_lv_cyp8b1' = 'LV xxx*, p = xxx',
    'FA_lv_srebp1c' = 'LV Srebp1c*, p = 0.043',
    "FA_lv_scd1" = "LV scd, p = 0.66"
)

dat.chol <- melt(gene_sub, id.vars='treatment', groups = 'treatment', 
              measure.vars=c("FA_lv_srebp1c", "FA_lv_scd1"))

significant_genes_chol <- c(
    'FA_lv_srebp1c' = 'LV Srebp1c*, p = 0.043',
    "FA_lv_scd1" = "LV scd, p = 0.66"
)


p4 <- ggplot(dat.chol, aes(treatment, log(value), fill=treatment), outlier.shape = NA)  +
    ylab("") +
    xlab("") +
    ggtitle("4. Fatty Acid Synthesis Genes") +
    geom_flat_violin(position=position_nudge(x=.1)) +
    geom_dotplot(binaxis="y", stackdir="down", dotsize=.35) +
    geom_boxplot(width=.1, position=position_nudge(x=.1)) +
    scale_x_discrete(expand=c(1,0)) +
    scale_fill_manual(values=c("#0072BF", "#CF524C")) +
    coord_flip() + 
    theme_bw() +
    theme(strip.text = element_text(face = "bold.italic", size = 12), 
          strip.background = element_rect(fill = "#99B6C2"),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.x = element_text(size = 12),
          axis.title = element_text(size = 15, face = "bold"),
          plot.margin = unit(c(0,1,-0.8,0.3), "cm"))

p4 <- p4 + facet_wrap(~ variable, labeller = as_labeller(significant_genes_chol), nrow = 1) + theme(legend.position = "none")
```


```{r combine plots}
ggg <-  ggpubr::ggarrange(p3, p, p2,
          heights = c(3.5, 3.4, 2.1),
          ncol = 1, nrow = 3)

ggg <-  ggpubr::ggarrange(p3, p, p2, p4,
          heights = c(3.5, 3.4, 2.1, 2.1),
          ncol = 1, nrow = 4)

allgenes <- ggpubr::ggarrange(gene_BA, NULL,
                              legend = "bottom",
                              ncol = 1, nrow = 2,
                              heights = c(5, 4))


allgenes2 <- ggpubr::ggarrange(gene_BA, p4,
                              legend = "bottom",
                              ncol = 1, nrow = 2,
                              heights = c(7, 2))

## final figure7:
ggpubr::ggarrange(allgenes, ggg, 
          labels = c("A", "B"),
          legend="bottom",
          ncol = 2, nrow = 1)

## final figure7-2:
ggpubr::ggarrange(allgenes2, ggg, 
          labels = c("A", "B"),
          legend="bottom",
          ncol = 2, nrow = 1)

ggsave(here("R26.png"), width = 16, height = 14, dpi = 1000)
```

